# Generated by Django 5.0.14 on 2026-04-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название темы')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500, verbose_name='термин')),
                ('translation', models.TextField(verbose_name='пояснение')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.topic', verbose_name='тема')),
            ],
            options={
                'verbose_name': 'историческая карточка',
                'verbose_name_plural': 'исторические карточки',
                'ordering': ['id'],
            },
        ),
    ]
