# Generated by Django 5.0.14 on 2026-04-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historycard',
            name='term',
            field=models.CharField(max_length=500, verbose_name='термин (лицевая сторона)'),
        ),
    ]
